default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: HRM_development

test:
  <<: *default
  database: HRM_test

production:
  <<: *default
  database: HRM_production
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
