default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: postgres

development:
  <<: *default
  database: Backend_development

test:
  <<: *default
  database: Backend_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>
  host: <%= ENV['HOST'] %>
  port: <%= ENV['PORT'] %>
