FROM node:16.10.0-alpine as build

WORKDIR /app

COPY ./Frontend/package.json ./app/package.json

RUN yarn install

COPY ./Frontend /app

RUN yarn add react-scripts
RUN yarn run build

FROM nginx:alpine

# COPY --from=build /nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

# RUN rm -rf ./*

COPY --from=build /app/build .
# COPY /nginx/nginx.conf /etc/nginx/conf.d

ENTRYPOINT ["nginx", "-g", "daemon off;"]
